package AppPackage;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrew
 */
public class ChangePass extends javax.swing.JFrame {

    /**
     * Creates new form ChangePass
     */
    public ChangePass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submitNewPass = new javax.swing.JButton();
        oldPass = new javax.swing.JPasswordField();
        newPass = new javax.swing.JPasswordField();
        confirmNewPass = new javax.swing.JPasswordField();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Old Password:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel2.setText("New Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel3.setText("Confirm New Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 30));

        submitNewPass.setText("Submit Changes");
        submitNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitNewPassActionPerformed(evt);
            }
        });
        getContentPane().add(submitNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, 30));
        getContentPane().add(oldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, -1));
        getContentPane().add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 110, -1));
        getContentPane().add(confirmNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 110, -1));

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 30));

        setBounds(0, 0, 431, 311);
    }// </editor-fold>//GEN-END:initComponents

    private void submitNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNewPassActionPerformed
        String password = "abc123"; //TODO get this from hidden file or wherever
        String userOldPass = new String(oldPass.getPassword());
        String userNewPass = new String(newPass.getPassword());
        String userConfirmNewPass = new String(confirmNewPass.getPassword());
        ArrayList<String> errors = new ArrayList();
        
        //validate password inputs
        if(!(userOldPass.equals(password))){
            errors.add("- Old password does not match records\n");
        }
        if(!(userNewPass.matches("(?i)^[a-z0-9]+$"))){
            errors.add("- Invalid format for new password, use numbers and letters only\n");
        }
        if(!(userNewPass.equals(userConfirmNewPass))){
            errors.add("- New password and Confirm new password do not match\n");
        }
        
        if(errors.size() > 0){
            String errorList = "";
            for (int i = 0; i < errors.size(); i++) {
                errorList = errorList + errors.get(i);
            }
            
            JOptionPane.showMessageDialog(null, errorList, "Input error", JOptionPane.ERROR_MESSAGE);
        }else{
            password = userNewPass; //TODO write to hidden file/wherever the password is stored
            JOptionPane.showMessageDialog(null, "Password Successfully Changed", "Password Changed", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            HospitalGUI hg = new HospitalGUI();
            hg.setVisible(true);
        }
    }//GEN-LAST:event_submitNewPassActionPerformed
    //disabled the default X button to close, and use this instead
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       this.dispose();
       HospitalGUI hg = new HospitalGUI();
       hg.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JPasswordField confirmNewPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField oldPass;
    private javax.swing.JButton submitNewPass;
    // End of variables declaration//GEN-END:variables
}
