/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import au.com.bytecode.opencsv.CSVReader;
import au.com.bytecode.opencsv.CSVWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrew
 */
public class ViewCsv extends javax.swing.JFrame {
    private Set<Integer> ignoreList = new HashSet<Integer>();
    private ArrayList<String[]> finalOutput = new ArrayList<String[]>();
    private final String filename = "Sample Records.csv";
    private final int barcodeIndex = 3;
    private final int transactionIndex = 5;
    
    /**
     * Creates new form ViewCsv
     */
    public ViewCsv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        submitPass = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        purge_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Input Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, 20));
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, -1));

        submitPass.setText("View CSV");
        submitPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPassActionPerformed(evt);
            }
        });
        getContentPane().add(submitPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 100, -1));

        goBack.setText("Go Back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        getContentPane().add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 80, -1));

        purge_button.setText("Purge");
        purge_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purge_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(purge_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 80, -1));

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void submitPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitPassActionPerformed
        String password = "abc123"; //TODO get this from hidden file/wherever
        String userPass = new String(passField.getPassword());
        
        if(userPass.equals(password)){
            try {
                Desktop.getDesktop().open(new File(filename));
            } catch (IOException ex) {
                Logger.getLogger(ViewCsv.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Incorrect Password", "Incorrect Password", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitPassActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        this.dispose();
        HospitalGUI hg = new HospitalGUI();
        hg.setVisible(true);
    }//GEN-LAST:event_goBackActionPerformed

    private void purge_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purge_buttonActionPerformed
        try {
            CSVReader reader = new CSVReader(new FileReader(filename));	
            List<String[]> entireHistory = reader.readAll();
            reader.close();
			
            for(int j=0;j<entireHistory.size();j++){
		String barcode = entireHistory.get(j)[barcodeIndex];
		String transaction = entireHistory.get(j)[transactionIndex];
				
		if(transaction.equals("Sign out")){
                    for(int i=j; i<entireHistory.size(); i++){
			if(barcode.equals(entireHistory.get(i)[barcodeIndex]) && (entireHistory.get(i)[transactionIndex]).equals("Return")){
                            ignoreList.add(j);
                            ignoreList.add(i);
			}//if
                    }//for
                }//if
            }//for

            for(int k=0; k<entireHistory.size(); k++){
		if(!(ignoreList.contains(k))){
                    finalOutput.add(entireHistory.get(k));
		}//if
            }//for
			
            CSVWriter writer = new CSVWriter(new FileWriter("test_write.csv", false));
            writer.writeAll(finalOutput);
            System.out.println(ignoreList.size()+ " items purged.");
            writer.close();
		
            } catch (FileNotFoundException e) {
		e.printStackTrace();
            } catch (IOException e) {
		e.printStackTrace();
            }
    }//GEN-LAST:event_purge_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCsv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton purge_button;
    private javax.swing.JButton submitPass;
    // End of variables declaration//GEN-END:variables
}
